// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCACf5tsm35YBiGzoTq4cXpKm5fIhZMlRM',
    appId: '1:1094865316700:web:7482df22a71ad223cf2f99',
    messagingSenderId: '1094865316700',
    projectId: 'food-delivery-app-d9956',
    authDomain: 'food-delivery-app-d9956.firebaseapp.com',
    storageBucket: 'food-delivery-app-d9956.firebasestorage.app',
    measurementId: 'G-K17W4CKFKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAddMjzynV-qrqyzYbIx1KmF9yEZ2Xs7Jc',
    appId: '1:1094865316700:android:5a72ab0f93908c27cf2f99',
    messagingSenderId: '1094865316700',
    projectId: 'food-delivery-app-d9956',
    storageBucket: 'food-delivery-app-d9956.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl8Mk1-DlrH6XrXTOCY45EXrKDyxYVKms',
    appId: '1:1094865316700:ios:cf51308f742a4745cf2f99',
    messagingSenderId: '1094865316700',
    projectId: 'food-delivery-app-d9956',
    storageBucket: 'food-delivery-app-d9956.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl8Mk1-DlrH6XrXTOCY45EXrKDyxYVKms',
    appId: '1:1094865316700:ios:cf51308f742a4745cf2f99',
    messagingSenderId: '1094865316700',
    projectId: 'food-delivery-app-d9956',
    storageBucket: 'food-delivery-app-d9956.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCACf5tsm35YBiGzoTq4cXpKm5fIhZMlRM',
    appId: '1:1094865316700:web:1a072e1da01c648bcf2f99',
    messagingSenderId: '1094865316700',
    projectId: 'food-delivery-app-d9956',
    authDomain: 'food-delivery-app-d9956.firebaseapp.com',
    storageBucket: 'food-delivery-app-d9956.firebasestorage.app',
    measurementId: 'G-V93Y5JGLEX',
  );
}
